# Generated by Django 5.2.12 on 2026-04-06 01:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('paper_json', models.JSONField(default=dict)),
                ('figures_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm_model', models.CharField(max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['canonical_id'], name='researcher__canonic_d4bbf3_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.TextField()),
                ('source_type', models.CharField(max_length=16)),
                ('input_display', models.CharField(max_length=255)),
                ('llm_model', models.CharField(max_length=64)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('progress', models.IntegerField(default=0)),
                ('stage', models.CharField(default='Queued', max_length=255)),
                ('current_step', models.CharField(default='paper', max_length=32)),
                ('error', models.TextField(blank=True, default='')),
                ('figure_parse_total', models.IntegerField(default=0)),
                ('figure_parse_current', models.IntegerField(default=0)),
                ('supplementary_figure_ids', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='missing', max_length=16)),
                ('missing_fields', models.JSONField(default=list)),
                ('source', models.CharField(default='parsed', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='researcher_ai_portal_app.workflowjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='workflowjob',
            index=models.Index(fields=['user', '-created_at'], name='researcher__user_id_1f1f6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='componentsnapshot',
            unique_together={('job', 'step')},
        ),
    ]
