# Generated by Django 5.2.12 on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_ai_portal_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowjob",
            name="parse_logs",
            field=models.JSONField(default=list),
        ),
    ]
