# Generated by Django 5.2.13 on 2026-04-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_ai_portal_app', '0002_workflowjob_parse_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowjob',
            name='graph_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
