# Generated by Django 5.2.12 on 2026-04-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_ai_portal_app', '0003_workflowjob_graph_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowjob',
            name='job_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workflowjob',
            name='status',
            field=models.CharField(default='queued', max_length=32),
        ),
    ]
