# Generated by Django 5.2.12 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_ai_portal_app", "0004_workflowjob_job_metadata_alter_workflowjob_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="papercache",
            name="assay_computational_overrides",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
